-- TABLE CREATION
CREATE TABLE "users" (
    user_id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- FETCH ALL ROWS
SELECT * FROM users

-- CLEAR ALL USER ROWS
DELETE FROM users;
ALTER SEQUENCE users_user_id_seq RESTART WITH 1;