-- TABLE CREATION
CREATE TABLE "users" (
    user_id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    is_verified BOOLEAN DEFAULT FALSE,
    email_verification_token VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- FETCH ALL ROWS
SELECT * FROM users

-- VERIFIED USERS, TOKEN IS GUARANTEED TO ALWAYS BE NULL
SELECT * FROM users WHERE email_verification_token IS NULL;

-- CLEAR ALL USER ROWS
DELETE FROM users;
ALTER SEQUENCE users_user_id_seq RESTART WITH 1;